blog/views.py
# core imports
import urllib
import re
import datetime
import pathlib

# 3rd party imports
import flask
from flask import current_app as app
from flask import render_template, request, Response
from playhouse.flask_utils import get_object_or_404, object_list

# local imports
import secret
from models import Entry, FTSEntry, db, MetaFileError, Series
import rss


bp = flask.Blueprint('bp', __name__)


#  def parse_markdown(markdown_path):
#      with open(markdown_path) as markdown_file:
#          title = markdown_file.readline().lstrip('# ').rstrip(' \r\n')
#          # TODO: only in math context
#          content = markdown_file.read().lstrip(' \r\n')
#          content = re.sub(r'\\\\', r'\\newline', content)
#      return title, content
#  
#  
#  def update_entry(entry, markdown_path, data_path):
#      entry.docid = markdown_path.name.split('_', 1)[0]
#      entry.title, entry.content = parse_markdown(markdown_path)
#      #  with open(markdown_path) as markdown_file:
#      #      entry.title = markdown_file.readline().lstrip('# ').rstrip(' \r\n')
#      #      entry.content = markdown_file.read().lstrip(' \r\n')
#      with open(data_path) as data_file:
#          # TODO: make more dynamic (do not requre slug, and such)
#          #  entry.title = data_file.readline().rstrip('\n').split(': ')[-1]
#          entry.slug = data_file.readline().rstrip('\n').split(': ')[-1]
#          entry.published = bool(data_file.readline().rstrip('\n').split(' ')[-1])
#          time_str = data_file.readline().rstrip('\n').split(': ')[-1]
#          if time_str:
#              entry.time = datetime.datetime(*map(int, time_str.split(',')))
#      if not time_str:
#          time_str = ','.join(map(str, datetime.datetime.now().timetuple()[:7]))
#          with open(data_path, 'a') as data_file:
#              data_file.write(f"Time: {time_str}\n")


@bp.route(f'/db/{secret.SECRET_DB_URL}/<docid>')
def post_blog(docid):
    markdown_file = data_file = None
    try:
        markdown_file = next(app.config["POSTS_MARKDOWN_DIR"].glob(f"{docid}_*.md"))
        data_file = next(app.config["POSTS_META_DIR"].glob(f"{docid}_*.meta"))
    except StopIteration:
        error = ""
        if markdown_file is None:
            error += ' - the markdown file does not exist\n'
        if data_file is None:
            error += ' - the data file does not exist\n'
        return error
    try:
        entry = Entry.create_or_update_from_disk(markdown_file, data_file)
    except MetaFileError as e:
        return str(e)
    #  update_entry(entry, markdown_file, data_file)
    with db.database.atomic():
        entry.save()
    return f"{docid} Success!"


@bp.route('/')
def index():
    search_query = request.args.get('q')
    if search_query:
        query = Entry.search(search_query)
    else:
        query = Entry.public().order_by(Entry.timestamp.desc())

    # The `object_list` helper will take a base query and then handle
    # paginating the results if there are more than 20. For more info see
    # the docs:
    # http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#object_list
    return object_list('index.html', query, search=search_query, check_bounds=False)


def send_data(folder, filename):
    filename = str(app.config["POSTS_STATIC_DIR"] / folder / filename)
    return flask.send_file(filename)


@bp.route('/blog_id/<slug>/',  defaults={'folder': None, 'filename': None})
@bp.route('/blog_id/<docid>/')
def document(docid, folder, filename):
    if folder is not None:
        return send_data(folder, filename)
    entry = get_object_or_404(Entry.public(), Entry.id == docid)
    return render_template('detail.html', entry=entry)


@bp.route('/blog/<slug>/',  defaults={'folder': None, 'filename': None})
@bp.route('/blog/<slug>/<folder>/<filename>')
def detail(slug, folder, filename):
    if folder is not None:
        return send_data(folder, filename)
    query = Entry.public()
    entry = get_object_or_404(query, Entry.slug == slug)
    return render_template('detail.html', entry=entry, series=Series(entry))


def get_feed_generator(feed_url):
    domain = pathlib.Path(app.config["DOMAIN"])
    fg = rss.get_feed(str(domain / feed_url))
    for entry in Entry.public().order_by(Entry.timestamp.desc()):
        rss.add_entry(fg, entry, domain)
    return fg


@bp.route('/feed/rss')
def rss_feed():
    feed = get_feed_generator('feed/rss').rss_str()
    return Response(feed, mimetype='application/rss+xml')
    #  response = make_response(fg.rss_str())
    #  response.headers.set('Content-Type', 'application/rss+xml')


#  @bp.route('/feed/atom')
#  def atom_feed():
#      return get_feed_generator().atom_str()
#  

@bp.errorhandler(404)
def not_found(exc):
    return Response('<h3>Not found</h3>'), 404


@bp.app_template_filter('clean_querystring')
def clean_querystring(request_args, *keys_to_remove, **new_values):
    # We'll use this template filter in the pagination include. This filter
    # will take the current URL and allow us to preserve the arguments in the
    # querystring while replacing any that we need to overwrite. For instance
    # if your URL is /?q=search+query&page=2 and we want to preserve the search
    # term but make a link to page 3, this filter will allow us to do that.
    querystring = dict((key, value) for key, value in request_args.items())
    for key in keys_to_remove:
        querystring.pop(key, None)
    querystring.update(new_values)
    return urllib.urlencode(querystring)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
#  @bp.before_request
#  def _db_connect():
#      db.database.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
#  @bp.teardown_request
#  def _db_close(exc):
#      if not db.database.is_closed():
#          db.database.close()

blog/templates/base.html
<!doctype html>
<html>
  <head>
    <title>Blog</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/blog.min.css') }}" />
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/hilite.css') }}" />
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/custom.css') }}" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    {% block extra_head %}{% endblock %}

    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"] ],
        processEscapes: true
        }
    });
    </script>_
    <script type="text/javascript"
    src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="{{ url_for('static', filename='js/jquery-1.11.0.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block extra_scripts %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('bp.index') }}">Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% block extra_header %}{% endblock %}
          </ul>
          {% block search_bar %}
            <form action="{{ url_for('bp.index') }}" class="navbar-form navbar-right" id="search-form" method="get" role="search">
              <div class="form-group">
                <input class="form-control" name="q" placeholder="Search" type="text" value="{% if search %}{{ search }}{% endif %}">
              </div>
            </form>
          {% endblock %}
        </div>
      </div>
    </div>

    <div class="container">
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ category }} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <p>{{ message }}</p>
        </div>
      {% endfor %}

      {% block page_header %}
        <div class="page-header">
          <h1>{% block content_title %}{% endblock %}</h1>
        </div>
      {% endblock %}

      {% block content %}{% endblock %}

      <footer>
        <hr />
      </footer>
    </div>
  </body>
</html>

blog/templates/detail.html
{% extends "base.html" %}

{% block title %}{{ entry.title }}{% endblock %}

{% block content_title %}{{ entry.title }}{% endblock %}

{% block extra_header %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
  <p>Created {{ entry.timestamp.strftime('%m/%d/%Y at %I:%M%p') }}</p>
  {{ entry.html_content }}
    {% if entry.series %}
        <hr>
        This is part {{ entry.part }} 
        <a href="../{{ series.last.slug }}">of {{ series.last.part }}</a>
        in the "{{ entry.series }}" Series.
            <br/>
        {% if series.previous %}
            Clik here to go to the
            <a href="../{{ series.previous.slug }}">previous post</a>
            <br/>
        {% endif %}
        {% if series.next %}
            Click here for the 
            <a href="../{{ series.next.slug }}">next post</a>
            <br/>
        {% endif %}
    {% endif %}
    <hr>
    <div style="text-align: center"> 
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
            <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" />
        </a>
        <br />This work is licensed under a
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
            Creative Commons Attribution-ShareAlike 4.0 International License
        </a>.
    </div>
    <hr>
    <div style="text-align: center"> 
    <a href=https://www.github.com/jancr/blog-posts//blob/master/posts/{{ entry.github_file }}>
    <i class="fa fa-github" style="font-size:24px"></i>
      Edit on GitHub! (if you find errors in this post)
  </a>

    </div>
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block title %}Blog entries{% endblock %}

{% block content_title %}{% if search %}Search "{{ search }}"{% else %}Blog entries{% endif %}{% endblock %}

{% block content %}
  {% for entry in object_list %}
    <h3>
      <a href="{{ url_for('bp.detail', slug=entry.slug) }}">
        {{ entry.title }}
      </a>
    </h3>
    <p>Created {{ entry.timestamp.strftime('%m/%d/%Y at %G:%I%p') }}</p>
  {% else %}
    <p>No entries have been created yet.</p>
  {% endfor %}
  {% include "includes/pagination.html" %}
{% endblock %}